# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:latest
      
    working_directory: ~/enzo-yang
    
    branches:
      only:
        - trigger

    steps:
      - checkout
      - run: npm install acyort -g
      - run: acyort init 
      - run: cp config.bak.yml config.yml 
      - run: git clone https://github.com/enzo-yang/theme-donob.git themes/donob 
      - run: acyort build  
      - run: git checkout .  
      - run: git checkout master
      - run: git reset --hard origin/master
      - run: cp -R public/* . 
      - run: rm config.bak.yml 
      - run: rm -R scripts themes public 
      - run: git add .
      - run: git config user.name "enzoyang"
      - run: git config user.email "divisoryang@gmail.com"
      - run: git commit -m "Updated by circleci - `date`"
      - run: git push https://${gh_token}@github.com/enzo-yang/enzo-yang.github.io.git master:master

